name: tennoji
description: A declarative, Flutter-inspired video editor library with a C++ backend.
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  characters: ^1.4.1
  code_assets: ^1.0.0
  ffi: ^2.1.0
  hooks: ^1.0.2
  meta: ^1.9.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
  ffigen: ^20.1.1

ffigen:
  output: 'lib/src/engine/bindings.dart'
  name: 'TennojiBindings'
  description: 'Bindings for tennoji native library'
  ffi-native:
    asset-id: 'package:tennoji/rina'
  headers:
    entry-points:
      - '../native/include/tennoji/engine.h'
    include-directives:
      - '../native/include/tennoji/*.h'
  compiler-opts:
    - '-Dbool=_Bool'
    - '-Dtrue=1'
    - '-Dfalse=0'
  functions:
    leaf:
      include: 
         - "rina_.*" 
    symbol-address:
      include:
        - "rina_.*_destroy"
  macros:
    include:
      - 'TENNOJI_*'
  typedefs:
    exclude:
      - '_*' # shut the fuck up
  silence-enum-warning: true
  
  preamble: |
    // ignore_for_file: always_specify_types
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
