// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:barsource/rina')
library;

import 'dart:ffi' as ffi;
import '' as self;

@ffi.Native<ffi.Void Function()>(isLeaf: true)
external void rina_tennoji();

@ffi.Native<
  ffi.Pointer<TennojiEngine> Function(ffi.Pointer<TennojiEngineConfig>)
>(isLeaf: true)
external ffi.Pointer<TennojiEngine> rina_engine_create(
  ffi.Pointer<TennojiEngineConfig> config,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiEngine>)>(isLeaf: true)
external void rina_engine_destroy(ffi.Pointer<TennojiEngine> engine);

@ffi.Native<
  ffi.Pointer<TennojiDecoder> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Pointer<ffi.Char>,
    ffi.UnsignedInt,
  )
>(symbol: 'rina_decoder_open', isLeaf: true)
external ffi.Pointer<TennojiDecoder> _rina_decoder_open(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<ffi.Char> uri,
  int accel,
);

ffi.Pointer<TennojiDecoder> rina_decoder_open(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<ffi.Char> uri,
  TennojiHWAccel accel,
) => _rina_decoder_open(engine, uri, accel.value);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiDecoder>)>(isLeaf: true)
external void rina_decoder_close(ffi.Pointer<TennojiDecoder> decoder);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiDecoder>, ffi.Int64)>(
  isLeaf: true,
)
external int rina_decoder_seek(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasImage> Function(
    ffi.Pointer<TennojiDecoder>,
    ffi.Int64,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasImage> rina_decoder_get_texture(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<TennojiDecoder>)>(isLeaf: true)
external int rina_decoder_duration(ffi.Pointer<TennojiDecoder> decoder);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<TennojiEngine>, ffi.Pointer<ffi.Char>)
>(isLeaf: true)
external int rina_media_source_duration(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<ffi.Char> uri,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiDecoder>, ffi.Int64)>(
  isLeaf: true,
)
external int rina_decoder_read_audio(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvas> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Int32,
    ffi.Int32,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvas> rina_canvas_create(
  ffi.Pointer<TennojiEngine> engine,
  int width,
  int height,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void rina_canvas_begin_recording(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<ffi.Pointer<TennojiPicture> Function(ffi.Pointer<TennojiCanvas>)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiPicture> rina_canvas_finish_recording(
  ffi.Pointer<TennojiCanvas> canvas,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void rina_canvas_destroy(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Uint32, ffi.Uint8)
>(isLeaf: true)
external void rina_canvas_draw_color(
  ffi.Pointer<TennojiCanvas> canvas,
  int color,
  int blendMode,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_paint(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_circle(
  ffi.Pointer<TennojiCanvas> canvas,
  double cx,
  double cy,
  double radius,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_rect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_rrect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
  double tlRx,
  double tlRy,
  double trRx,
  double trRy,
  double blRx,
  double blRy,
  double brRx,
  double brRy,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_image_rect(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasImage> image,
  double srcLeft,
  double srcTop,
  double srcWidth,
  double srcHeight,
  double dstLeft,
  double dstTop,
  double dstWidth,
  double dstHeight,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_image(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasImage> image,
  double dx,
  double dy,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiParagraph>,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_canvas_draw_paragraph(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiParagraph> paragraph,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Pointer<TennojiPicture>)
>(isLeaf: true)
external void rina_canvas_draw_picture(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiPicture> picture,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external void rina_canvas_draw_path(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<TennojiCanvasPaintMetadata> paintData,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void rina_canvas_save(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void rina_canvas_restore(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_canvas_translate(
  ffi.Pointer<TennojiCanvas> canvas,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Pointer<ffi.Float>)
>(isLeaf: true)
external void rina_canvas_transform(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_canvas_scale(
  ffi.Pointer<TennojiCanvas> canvas,
  double sx,
  double sy,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_canvas_skew(
  ffi.Pointer<TennojiCanvas> canvas,
  double sx,
  double sy,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float)>(
  isLeaf: true,
)
external void rina_canvas_rotate(
  ffi.Pointer<TennojiCanvas> canvas,
  double degrees,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_canvas_clip_rect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
  bool doAntiAlias,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_canvas_clip_rrect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
  double tlRx,
  double tlRy,
  double trRx,
  double trRy,
  double blRx,
  double blRy,
  double brRx,
  double brRy,
  bool doAntiAlias,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
  )
>(isLeaf: true)
external int rina_canvas_save_layer(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasPaintMetadata> paint,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<TennojiCanvas>, ffi.Pointer<TennojiImageFilter>)
>(isLeaf: true)
external int rina_canvas_save_layer_rec(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiImageFilter> filter,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCanvas>, ffi.Uint8)>(
  isLeaf: true,
)
external int rina_canvas_save_layer_alpha(
  ffi.Pointer<TennojiCanvas> canvas,
  int alpha,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external int rina_canvas_get_save_count(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void rina_canvas_clear(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<
  ffi.Pointer<TennojiCanvasImage> Function(
    ffi.Pointer<TennojiPicture>,
    ffi.Pointer<TennojiEngine>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasImage> rina_picture_to_image(
  ffi.Pointer<TennojiPicture> picture,
  ffi.Pointer<TennojiEngine> engine,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiPicture>)>(isLeaf: true)
external void rina_picture_destroy(ffi.Pointer<TennojiPicture> picture);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiPicture>)>(isLeaf: true)
external int rina_picture_approximate_bytes_used(
  ffi.Pointer<TennojiPicture> picture,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiPicture>)>(isLeaf: true)
external int rina_picture_approximate_op_count(
  ffi.Pointer<TennojiPicture> picture,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasImage>)>(isLeaf: true)
external void rina_texture_destroy(ffi.Pointer<TennojiCanvasImage> texture);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiEngine>)>(isLeaf: true)
external void rina_engine_flush_textures(ffi.Pointer<TennojiEngine> engine);

@ffi.Native<
  ffi.Pointer<TennojiCodec> Function(ffi.Pointer<ffi.Uint8>, ffi.Uint64)
>(isLeaf: true)
external ffi.Pointer<TennojiCodec> rina_codec_from_encoded(
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

@ffi.Native<ffi.Pointer<TennojiCodec> Function(ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiCodec> rina_codec_from_file(
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCodec>)>(isLeaf: true)
external void rina_codec_destroy(ffi.Pointer<TennojiCodec> codec);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCodec>)>(isLeaf: true)
external int rina_codec_get_frame_count(ffi.Pointer<TennojiCodec> codec);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCodec>)>(isLeaf: true)
external int rina_codec_get_repetition_count(ffi.Pointer<TennojiCodec> codec);

@ffi.Native<
  ffi.Pointer<TennojiFrameInfo> Function(ffi.Pointer<TennojiCodec>, ffi.Int)
>(isLeaf: true)
external ffi.Pointer<TennojiFrameInfo> rina_codec_get_frame_info(
  ffi.Pointer<TennojiCodec> codec,
  int index,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiFrameInfo>)>(isLeaf: true)
external void rina_frame_info_destroy(ffi.Pointer<TennojiFrameInfo> info);

@ffi.Native<
  ffi.Pointer<TennojiImageDescriptor> Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiImageDescriptor> rina_idesc_from_encoded(
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

@ffi.Native<
  ffi.Pointer<TennojiImageDescriptor> Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int8,
    ffi.Int8,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiImageDescriptor> rina_idesc_from_raw(
  ffi.Pointer<ffi.Uint8> data,
  int width,
  int height,
  int rowBytes,
  int pixelFormat,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<TennojiImageDescriptor>)>(
  isLeaf: true,
)
external int rina_idesc_get_width(
  ffi.Pointer<TennojiImageDescriptor> descriptor,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<TennojiImageDescriptor>)>(
  isLeaf: true,
)
external int rina_idesc_get_height(
  ffi.Pointer<TennojiImageDescriptor> descriptor,
);

@ffi.Native<
  ffi.Pointer<TennojiCodec> Function(
    ffi.Pointer<TennojiImageDescriptor>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint8,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCodec> rina_idesc_instantiate_codec(
  ffi.Pointer<TennojiImageDescriptor> descriptor,
  int targetWidth,
  int targetHeight,
  int targetPixelFormat,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiImageDescriptor>)>(
  isLeaf: true,
)
external void rina_idesc_destroy(
  ffi.Pointer<TennojiImageDescriptor> descriptor,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Pointer<TennojiCanvasImage>,
  )
>(isLeaf: true)
external bool rina_texture_equals(
  ffi.Pointer<TennojiCanvasImage> tex1,
  ffi.Pointer<TennojiCanvasImage> tex2,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCanvasImage>)>(isLeaf: true)
external int rina_texture_get_width(ffi.Pointer<TennojiCanvasImage> texture);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCanvasImage>)>(isLeaf: true)
external int rina_texture_get_height(ffi.Pointer<TennojiCanvasImage> texture);

@ffi.Native<
  ffi.Pointer<TennojiCanvasImage> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Int,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Int64,
    ffi.Uint32,
    ffi.Uint64,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasImage> rina_texture_from_dmabuf(
  ffi.Pointer<TennojiEngine> engine,
  int dmaBufFd,
  int width,
  int height,
  int rowBytes,
  int offsetBytes,
  int pixelFormat,
  int modifier,
);

@ffi.Native<
  ffi.Pointer<TennojiEncoder> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Pointer<TennojiEncoderConfig>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiEncoder> rina_encoder_create(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<TennojiEncoderConfig> config,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<TennojiEncoder>, ffi.Pointer<TennojiCanvas>)
>(isLeaf: true)
external int rina_encoder_write_frame(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiCanvas> canvas,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TennojiEncoder>,
    ffi.Pointer<TennojiDecoder>,
    ffi.Int64,
  )
>(isLeaf: true)
external int rina_encoder_write_audio(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiDecoder> audio_decoder,
  int duration_us,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<TennojiEncoder>, ffi.Pointer<TennojiDecoder>)
>(isLeaf: true)
external int rina_encoder_drain_audio_queue(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiDecoder> decoder,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TennojiDecoder>,
    ffi.Int64,
    ffi.Pointer<ffi.Float>,
    ffi.Int,
    ffi.Int,
  )
>(isLeaf: true)
external int rina_decoder_read_audio_samples(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
  ffi.Pointer<ffi.Float> samples_out,
  int sample_count,
  int sample_rate,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TennojiEncoder>,
    ffi.Pointer<ffi.Float>,
    ffi.Int,
    ffi.Int,
    ffi.Int,
  )
>(isLeaf: true)
external int rina_encoder_write_audio_samples(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<ffi.Float> samples,
  int sample_count,
  int sample_rate,
  int channels,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiEncoder>)>(isLeaf: true)
external int rina_encoder_finalize(ffi.Pointer<TennojiEncoder> encoder);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiEncoder>)>(isLeaf: true)
external void rina_encoder_destroy(ffi.Pointer<TennojiEncoder> encoder);

@ffi.Native<
  ffi.Pointer<TennojiParagraphBuilder> Function(
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Uint32,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiParagraphBuilder> rina_paragraph_builder_create(
  ffi.Pointer<ffi.Int32> encodedStyle,
  ffi.Pointer<ffi.Uint8> strutData,
  bool hasStrutData,
  ffi.Pointer<ffi.Char> fontFamily,
  ffi.Pointer<ffi.Pointer<ffi.Char>> strutFontFamilies,
  int sffLen,
  ffi.Pointer<ffi.Char> ellipsis,
  ffi.Pointer<ffi.Char> locale,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiParagraphBuilder>,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Uint32,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
    ffi.Pointer<TennojiCanvasPaintMetadata>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>(isLeaf: true)
external void rina_paragraph_builder_push_style(
  ffi.Pointer<TennojiParagraphBuilder> builder,
  ffi.Pointer<ffi.Int32> encoded,
  ffi.Pointer<ffi.Pointer<ffi.Char>> fontFamilies,
  int ffLength,
  double fontSize,
  double letterSpacing,
  double wordSpacing,
  double height,
  double decorationThickness,
  ffi.Pointer<ffi.Char> locale,
  ffi.Pointer<TennojiCanvasPaintMetadata> background,
  ffi.Pointer<TennojiCanvasPaintMetadata> foreground,
  ffi.Pointer<ffi.Uint32> shadowsData,
  ffi.Pointer<ffi.Uint32> fontFeaturesData,
  ffi.Pointer<ffi.Uint32> fontVariationsData,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiParagraphBuilder>)>(
  isLeaf: true,
)
external void rina_paragraph_builder_pop(
  ffi.Pointer<TennojiParagraphBuilder> builder,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiParagraphBuilder>, ffi.Pointer<ffi.Char>)
>(isLeaf: true)
external void rina_paragraph_builder_add_text(
  ffi.Pointer<TennojiParagraphBuilder> builder,
  ffi.Pointer<ffi.Char> text,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiParagraphBuilder>,
    ffi.Float,
    ffi.Float,
    ffi.Uint32,
    ffi.Float,
    ffi.Uint32,
  )
>(isLeaf: true)
external void rina_paragraph_builder_add_placeholder(
  ffi.Pointer<TennojiParagraphBuilder> builder,
  double width,
  double height,
  int alignment,
  double baselineOffset,
  int baseline,
);

@ffi.Native<
  ffi.Pointer<TennojiParagraph> Function(ffi.Pointer<TennojiParagraphBuilder>)
>(isLeaf: true)
external ffi.Pointer<TennojiParagraph> rina_paragraph_builder_build(
  ffi.Pointer<TennojiParagraphBuilder> builder,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiParagraphBuilder>)>(
  isLeaf: true,
)
external void rina_paragraph_builder_destroy(
  ffi.Pointer<TennojiParagraphBuilder> builder,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32, ffi.Pointer<ffi.Char>)
>(isLeaf: true)
external void rina_load_font_from_list(
  ffi.Pointer<ffi.Uint8> data,
  int length,
  ffi.Pointer<ffi.Char> fontFamily,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external bool rina_load_font_from_file(
  ffi.Pointer<ffi.Char> filePath,
  ffi.Pointer<ffi.Char> fontFamily,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external void rina_paragraph_destroy(ffi.Pointer<TennojiParagraph> paragraph);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_width(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_height(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_longest_line(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_min_intrinsic_width(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_max_intrinsic_width(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_alphabetic_baseline(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external double rina_paragraph_get_ideographic_baseline(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external bool rina_paragraph_did_exceed_max_lines(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiParagraph>, ffi.Double)>(
  isLeaf: true,
)
external void rina_paragraph_layout(
  ffi.Pointer<TennojiParagraph> paragraph,
  double width,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(
    ffi.Pointer<TennojiParagraph>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint8,
    ffi.Uint8,
  )
>(isLeaf: true)
external ffi.Pointer<ffi.Float> rina_paragraph_get_boxes_for_range(
  ffi.Pointer<TennojiParagraph> paragraph,
  int start,
  int end,
  int boxHeightStyle,
  int boxWidthStyle,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiParagraph>)>(
  isLeaf: true,
)
external ffi.Pointer<ffi.Float> rina_paragraph_get_boxes_for_placeholders(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(
    ffi.Pointer<TennojiParagraph>,
    ffi.Double,
    ffi.Double,
  )
>(isLeaf: true)
external ffi.Pointer<ffi.Int32> rina_paragraph_get_position_for_offset(
  ffi.Pointer<TennojiParagraph> paragraph,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(ffi.Pointer<TennojiParagraph>, ffi.Int32)
>(isLeaf: true)
external ffi.Pointer<ffi.Int32> rina_paragraph_get_glyph_info_at(
  ffi.Pointer<TennojiParagraph> paragraph,
  int codeUnitOffset,
);

@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(
    ffi.Pointer<TennojiParagraph>,
    ffi.Double,
    ffi.Double,
  )
>(isLeaf: true)
external ffi.Pointer<ffi.Int32> rina_paragraph_get_glyph_info_for_offset(
  ffi.Pointer<TennojiParagraph> paragraph,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(ffi.Pointer<TennojiParagraph>, ffi.Int64)
>(isLeaf: true)
external ffi.Pointer<ffi.Int32> rina_paragraph_get_word_boundary(
  ffi.Pointer<TennojiParagraph> paragraph,
  int characterPos,
);

@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(ffi.Pointer<TennojiParagraph>, ffi.Int64)
>(isLeaf: true)
external ffi.Pointer<ffi.Int32> rina_paragraph_get_line_boundary(
  ffi.Pointer<TennojiParagraph> paragraph,
  int offset,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiParagraph>)>(
  isLeaf: true,
)
external ffi.Pointer<ffi.Float> rina_paragraph_compute_line_metrics(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiParagraph>, ffi.Uint64)
>(isLeaf: true)
external ffi.Pointer<ffi.Float> rina_paragraph_get_line_metrics_at(
  ffi.Pointer<TennojiParagraph> paragraph,
  int lineNumber,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<TennojiParagraph>)>(isLeaf: true)
external int rina_paragraph_get_number_of_lines(
  ffi.Pointer<TennojiParagraph> paragraph,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<TennojiParagraph>, ffi.Int64)>(
  isLeaf: true,
)
external int rina_paragraph_get_line_number_at(
  ffi.Pointer<TennojiParagraph> paragraph,
  int codeUnitOffset,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external bool rina_rsuperellipse_contains(
  double px,
  double py,
  double left,
  double top,
  double right,
  double bottom,
  double tlRx,
  double tlRy,
  double trRx,
  double trRy,
  double blRx,
  double blRy,
  double brRx,
  double brRy,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasVertices> Function(
    ffi.Uint8,
    ffi.Uint64,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Uint16>,
    ffi.Uint64,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasVertices> rina_vertices_init(
  int mode,
  int length,
  ffi.Pointer<ffi.Float> positions,
  ffi.Pointer<ffi.Float> textureCoordinates,
  ffi.Pointer<ffi.Int32> colors,
  ffi.Pointer<ffi.Uint16> indices,
  int iLength,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasVertices>)>(isLeaf: true)
external void rina_vertices_destroy(
  ffi.Pointer<TennojiCanvasVertices> vertices,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasVertices>,
    ffi.Uint32,
    ffi.Uint32,
  )
>(isLeaf: true)
external void rina_canvas_draw_vertices(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasVertices> vertices,
  int blendMode,
  int color,
);

@ffi.Native<
  ffi.Pointer<TennojiShader> Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiShader> rina_gradient_create_linear(
  double x0,
  double y0,
  double x1,
  double y1,
  ffi.Pointer<ffi.Float> colors,
  ffi.Pointer<ffi.Float> stops,
  int length,
  int tileMode,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Pointer<TennojiShader> Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiShader> rina_gradient_create_radial(
  double cx,
  double cy,
  double radius,
  ffi.Pointer<ffi.Float> colors,
  ffi.Pointer<ffi.Float> stops,
  int length,
  int tileMode,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Pointer<TennojiShader> Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiShader> rina_gradient_create_sweep(
  double cx,
  double cy,
  double startAngle,
  double endAngle,
  ffi.Pointer<ffi.Float> colors,
  ffi.Pointer<ffi.Float> stops,
  int length,
  int tileMode,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Pointer<TennojiShader> Function(
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiShader> rina_gradient_create_conical(
  double startCx,
  double startCy,
  double startRadius,
  double endCx,
  double endCy,
  double endRadius,
  ffi.Pointer<ffi.Float> colors,
  ffi.Pointer<ffi.Float> stops,
  int length,
  int tileMode,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Pointer<TennojiShader> Function(
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiShader> rina_image_shader_create(
  ffi.Pointer<TennojiCanvasImage> image,
  int tileModeX,
  int tileModeY,
  int filterQuality,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiShader>)>(isLeaf: true)
external void rina_shader_destroy(ffi.Pointer<TennojiShader> shader);

@ffi.Native<TennojiFragmentProgramResult Function(ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external TennojiFragmentProgramResult rina_fragment_create(
  ffi.Pointer<ffi.Char> filePath,
);

@ffi.Native<
  ffi.Pointer<TennojiFragmentShader> Function(
    ffi.Pointer<TennojiFragmentProgram>,
    ffi.Uint64,
    ffi.Uint64,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiFragmentShader> rina_fragment_create_shader(
  ffi.Pointer<TennojiFragmentProgram> prog,
  int floatCount,
  int samplerCount,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiFragmentShader>)
>(isLeaf: true)
external ffi.Pointer<ffi.Float> rina_fragment_shader_get_uniform_buffer(
  ffi.Pointer<TennojiFragmentShader> shader,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiFragmentShader>,
    ffi.Uint64,
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Uint8,
  )
>(isLeaf: true)
external void rina_fragment_shader_set_image_sampler(
  ffi.Pointer<TennojiFragmentShader> shader,
  int index,
  ffi.Pointer<TennojiCanvasImage> image,
  int filterQuality,
);

@ffi.Native<ffi.Pointer<TennojiCanvasPath> Function()>(isLeaf: true)
external ffi.Pointer<TennojiCanvasPath> rina_path_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasPath>)>(isLeaf: true)
external void rina_path_destroy(ffi.Pointer<TennojiCanvasPath> path);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<TennojiCanvasPath>)>(isLeaf: true)
external int rina_path_get_fill_type(ffi.Pointer<TennojiCanvasPath> path);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Uint8)>(
  isLeaf: true,
)
external void rina_path_set_fill_type(
  ffi.Pointer<TennojiCanvasPath> path,
  int type,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_path_move_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x,
  double y,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_path_relative_move_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_path_line_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x,
  double y,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_path_relative_line_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_quadratic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_relative_quadratic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_cubic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
  double x3,
  double y3,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_relative_cubic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
  double x3,
  double y3,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_conic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
  double w,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_relative_conic_to(
  ffi.Pointer<TennojiCanvasPath> path,
  double x1,
  double y1,
  double x2,
  double y2,
  double w,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_path_arc_to_rect(
  ffi.Pointer<TennojiCanvasPath> path,
  double left,
  double top,
  double right,
  double bottom,
  double startAngle,
  double sweepAngle,
  bool forceMoveTo,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_path_arc_to_point(
  ffi.Pointer<TennojiCanvasPath> path,
  double arcEndX,
  double arcEndY,
  double radiusX,
  double radiusY,
  double rotation,
  bool largeArc,
  bool clockwise,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_path_relative_arc_to_point(
  ffi.Pointer<TennojiCanvasPath> path,
  double arcEndDeltaX,
  double arcEndDeltaY,
  double radiusX,
  double radiusY,
  double rotation,
  bool largeArc,
  bool clockwise,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasPath> Function(ffi.Pointer<TennojiCanvasPath>)
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasPath> rina_path_clone(
  ffi.Pointer<TennojiCanvasPath> path,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_add_rect(
  ffi.Pointer<TennojiCanvasPath> path,
  double l,
  double t,
  double r,
  double b,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_add_oval(
  ffi.Pointer<TennojiCanvasPath> path,
  double l,
  double t,
  double r,
  double b,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_add_arc(
  ffi.Pointer<TennojiCanvasPath> path,
  double l,
  double t,
  double r,
  double b,
  double startAngle,
  double sweepAngle,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint64,
    ffi.Bool,
  )
>(isLeaf: true)
external void rina_path_add_polygon(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<ffi.Float> points,
  int unencoded_length,
  bool close,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Pointer<ffi.Float>)
>(isLeaf: true)
external void rina_path_add_rrect(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<ffi.Float> rrectData,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Pointer<ffi.Float>)
>(isLeaf: true)
external void rina_path_add_rsuperellipse(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<ffi.Float> rsuperellipseData,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Bool,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void rina_path_add_path(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<TennojiCanvasPath> otherPath,
  bool extend,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Bool,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Float>,
  )
>(isLeaf: true)
external void rina_path_add_path_with_matrix(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<TennojiCanvasPath> otherPath,
  bool extend,
  double dx,
  double dy,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasPath>)>(isLeaf: true)
external void rina_path_close(ffi.Pointer<TennojiCanvasPath> path);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasPath>)>(isLeaf: true)
external void rina_path_reset(ffi.Pointer<TennojiCanvasPath> path);

@ffi.Native<
  ffi.Bool Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external bool rina_path_contains(
  ffi.Pointer<TennojiCanvasPath> path,
  double x,
  double y,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void rina_path_shift(
  ffi.Pointer<TennojiCanvasPath> path,
  double x,
  double y,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvasPath>, ffi.Pointer<ffi.Float>)
>(isLeaf: true)
external void rina_path_transform(
  ffi.Pointer<TennojiCanvasPath> path,
  ffi.Pointer<ffi.Float> matrix4,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Int,
  )
>(isLeaf: true)
external bool rina_path_combine_op(
  ffi.Pointer<TennojiCanvasPath> resultPath,
  ffi.Pointer<TennojiCanvasPath> path1,
  ffi.Pointer<TennojiCanvasPath> path2,
  int operationId,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiCanvasPath>)>(
  isLeaf: true,
)
external ffi.Pointer<ffi.Float> rina_path_get_bounds(
  ffi.Pointer<TennojiCanvasPath> path,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<TennojiCanvasPath>)>(
  isLeaf: true,
)
external ffi.Pointer<ffi.Float> rina_path_get_tight_bounds(
  ffi.Pointer<TennojiCanvasPath> path,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasPathMeasure> Function(
    ffi.Pointer<TennojiCanvasPath>,
    ffi.Bool,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasPathMeasure> rina_path_measure_create(
  ffi.Pointer<TennojiCanvasPath> path,
  bool forceClose,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasPathMeasure>)>(
  isLeaf: true,
)
external void rina_path_measure_destroy(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
);

@ffi.Native<
  ffi.Double Function(ffi.Pointer<TennojiCanvasPathMeasure>, ffi.Int32)
>(isLeaf: true)
external double rina_path_measure_length(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
  int contourIndex,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(
    ffi.Pointer<TennojiCanvasPathMeasure>,
    ffi.Int32,
    ffi.Double,
  )
>(isLeaf: true)
external ffi.Pointer<ffi.Float> rina_path_measure_tangent_for_offset(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
  int contourIndex,
  double distance,
);

@ffi.Native<
  ffi.Bool Function(ffi.Pointer<TennojiCanvasPathMeasure>, ffi.Int32)
>(isLeaf: true)
external bool rina_path_measure_closed(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
  int contourIndex,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasPath> Function(
    ffi.Pointer<TennojiCanvasPathMeasure>,
    ffi.Int32,
    ffi.Double,
    ffi.Double,
    ffi.Bool,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasPath> rina_path_measure_extract(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
  int contourIndex,
  double start,
  double end,
  bool startWithMoveTo,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<TennojiCanvasPathMeasure>)>(
  isLeaf: true,
)
external bool rina_path_measure_next_contour(
  ffi.Pointer<TennojiCanvasPathMeasure> measure,
);

@ffi.Native<ffi.Pointer<TennojiColorFilter> Function(ffi.Uint32, ffi.Uint8)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiColorFilter> rina_color_filter_create_mode(
  int color,
  int blendMode,
);

@ffi.Native<ffi.Pointer<TennojiColorFilter> Function(ffi.Pointer<ffi.Float>)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiColorFilter> rina_color_filter_create_matrix(
  ffi.Pointer<ffi.Float> matrix20,
);

@ffi.Native<ffi.Pointer<TennojiColorFilter> Function()>(isLeaf: true)
external ffi.Pointer<TennojiColorFilter>
rina_color_filter_create_srgb2linear_gamma();

@ffi.Native<ffi.Pointer<TennojiColorFilter> Function()>(isLeaf: true)
external ffi.Pointer<TennojiColorFilter>
rina_color_filter_create_linear2srgb_gamma();

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiColorFilter>)>(isLeaf: true)
external void rina_color_filter_destroy(ffi.Pointer<TennojiColorFilter> color);

@ffi.Native<
  ffi.Pointer<TennojiImageFilter> Function(
    ffi.Float,
    ffi.Float,
    ffi.Uint8,
    ffi.Bool,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_blur(
  double sigmaX,
  double sigmaY,
  int tileMode,
  bool bounded,
  double boundsLeft,
  double boundsTop,
  double boundsRight,
  double boundsBottom,
);

@ffi.Native<ffi.Pointer<TennojiImageFilter> Function(ffi.Float, ffi.Float)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_dilate(
  double radiusX,
  double radiusY,
);

@ffi.Native<ffi.Pointer<TennojiImageFilter> Function(ffi.Float, ffi.Float)>(
  isLeaf: true,
)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_erode(
  double radiusX,
  double radiusY,
);

@ffi.Native<
  ffi.Pointer<TennojiImageFilter> Function(ffi.Pointer<ffi.Float>, ffi.Uint8)
>(isLeaf: true)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_matrix(
  ffi.Pointer<ffi.Float> matrix4,
  int filterQuality,
);

@ffi.Native<
  ffi.Pointer<TennojiImageFilter> Function(ffi.Pointer<TennojiColorFilter>)
>(isLeaf: true)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_from_cf(
  ffi.Pointer<TennojiColorFilter> filter,
);

@ffi.Native<
  ffi.Pointer<TennojiImageFilter> Function(
    ffi.Pointer<TennojiImageFilter>,
    ffi.Pointer<TennojiImageFilter>,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiImageFilter> rina_image_filter_create_composed(
  ffi.Pointer<TennojiImageFilter> outer,
  ffi.Pointer<TennojiImageFilter> inner,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiImageFilter>)>(isLeaf: true)
external void rina_image_filter_destroy(ffi.Pointer<TennojiImageFilter> filter);

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiEngine>)>>
  get rina_engine_destroy => ffi.Native.addressOf(self.rina_engine_destroy);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>>
  get rina_canvas_destroy => ffi.Native.addressOf(self.rina_canvas_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiPicture>)>
  >
  get rina_picture_destroy => ffi.Native.addressOf(self.rina_picture_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCanvasImage>)>
  >
  get rina_texture_destroy => ffi.Native.addressOf(self.rina_texture_destroy);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCodec>)>>
  get rina_codec_destroy => ffi.Native.addressOf(self.rina_codec_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiFrameInfo>)>
  >
  get rina_frame_info_destroy =>
      ffi.Native.addressOf(self.rina_frame_info_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiImageDescriptor>)>
  >
  get rina_idesc_destroy => ffi.Native.addressOf(self.rina_idesc_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiEncoder>)>
  >
  get rina_encoder_destroy => ffi.Native.addressOf(self.rina_encoder_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiParagraphBuilder>)>
  >
  get rina_paragraph_builder_destroy =>
      ffi.Native.addressOf(self.rina_paragraph_builder_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiParagraph>)>
  >
  get rina_paragraph_destroy =>
      ffi.Native.addressOf(self.rina_paragraph_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCanvasVertices>)>
  >
  get rina_vertices_destroy => ffi.Native.addressOf(self.rina_vertices_destroy);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiShader>)>>
  get rina_shader_destroy => ffi.Native.addressOf(self.rina_shader_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCanvasPath>)>
  >
  get rina_path_destroy => ffi.Native.addressOf(self.rina_path_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiCanvasPathMeasure>)>
  >
  get rina_path_measure_destroy =>
      ffi.Native.addressOf(self.rina_path_measure_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiColorFilter>)>
  >
  get rina_color_filter_destroy =>
      ffi.Native.addressOf(self.rina_color_filter_destroy);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TennojiImageFilter>)>
  >
  get rina_image_filter_destroy =>
      ffi.Native.addressOf(self.rina_image_filter_destroy);
}

final class TennojiEngine extends ffi.Opaque {}

final class TennojiDecoder extends ffi.Opaque {}

final class TennojiEncoder extends ffi.Opaque {}

final class TennojiTexture extends ffi.Opaque {}

final class TennojiCanvas extends ffi.Opaque {}

final class TennojiParagraphBuilder extends ffi.Opaque {}

final class TennojiParagraph extends ffi.Opaque {}

final class TennojiCanvasImage extends ffi.Opaque {}

final class TennojiCodec extends ffi.Opaque {}

final class TennojiImageDescriptor extends ffi.Opaque {}

final class TennojiCanvasVertices extends ffi.Opaque {}

final class TennojiCanvasPath extends ffi.Opaque {}

final class TennojiCanvasPathMeasure extends ffi.Opaque {}

final class TennojiShader extends ffi.Opaque {}

final class TennojiFragmentProgram extends ffi.Opaque {}

final class TennojiFragmentProgramResult extends ffi.Struct {
  external ffi.Pointer<TennojiFragmentProgram> result;

  external ffi.Pointer<ffi.Char> errorDetails;
}

final class TennojiFragmentShader extends ffi.Opaque {}

final class TennojiColorFilter extends ffi.Opaque {}

final class TennojiImageFilter extends ffi.Opaque {}

final class TennojiPicture extends ffi.Opaque {}

final class TennojiFrameInfo extends ffi.Struct {
  @ffi.Int64()
  external int durationMs;

  external ffi.Pointer<TennojiCanvasImage> image;
}

enum TennojiHWAccel {
  TENNOJI_HW_ACCEL_AUTO(0),
  TENNOJI_HW_ACCEL_NONE(1);

  final int value;
  const TennojiHWAccel(this.value);

  static TennojiHWAccel fromValue(int value) => switch (value) {
    0 => TENNOJI_HW_ACCEL_AUTO,
    1 => TENNOJI_HW_ACCEL_NONE,
    _ => throw ArgumentError('Unknown value for TennojiHWAccel: $value'),
  };
}

enum TennojiOutputMode {
  TENNOJI_OUTPUT_MODE_LOCAL(0),
  TENNOJI_OUTPUT_MODE_YOUTUBE_STREAM(1);

  final int value;
  const TennojiOutputMode(this.value);

  static TennojiOutputMode fromValue(int value) => switch (value) {
    0 => TENNOJI_OUTPUT_MODE_LOCAL,
    1 => TENNOJI_OUTPUT_MODE_YOUTUBE_STREAM,
    _ => throw ArgumentError('Unknown value for TennojiOutputMode: $value'),
  };
}

final class TennojiEngineConfig extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int fps;

  external ffi.Pointer<ffi.Char> gpu_backend;
}

final class TennojiEncoderConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> output_path;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int fps;

  external ffi.Pointer<ffi.Char> video_codec;

  external ffi.Pointer<ffi.Char> audio_codec;

  @ffi.Int32()
  external int audio_sample_rate;

  @ffi.Int32()
  external int audio_channels;

  @ffi.Int32()
  external int output_mode;
}

final class TennojiCanvasPaintMetadata extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> encodedData;

  external ffi.Pointer<TennojiShader> shader;

  external ffi.Pointer<TennojiColorFilter> colorFilter;

  external ffi.Pointer<TennojiImageFilter> imageFilter;
}
