// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:tennoji/rina')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<TennojiEngine> Function(ffi.Pointer<TennojiEngineConfig>)
>()
external ffi.Pointer<TennojiEngine> tennoji_engine_create(
  ffi.Pointer<TennojiEngineConfig> config,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiEngine>)>()
external void tennoji_engine_destroy(ffi.Pointer<TennojiEngine> engine);

@ffi.Native<
  ffi.Pointer<TennojiDecoder> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Pointer<ffi.Char>,
    ffi.UnsignedInt,
  )
>(symbol: 'tennoji_decoder_open')
external ffi.Pointer<TennojiDecoder> _tennoji_decoder_open(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<ffi.Char> uri,
  int accel,
);

ffi.Pointer<TennojiDecoder> tennoji_decoder_open(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<ffi.Char> uri,
  TennojiHWAccel accel,
) => _tennoji_decoder_open(engine, uri, accel.value);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiDecoder>)>()
external void tennoji_decoder_close(ffi.Pointer<TennojiDecoder> decoder);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiDecoder>, ffi.Int64)>()
external int tennoji_decoder_seek(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvasImage> Function(
    ffi.Pointer<TennojiDecoder>,
    ffi.Int64,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvasImage> tennoji_decoder_get_texture(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<TennojiDecoder>)>(isLeaf: true)
external int tennoji_decoder_duration(ffi.Pointer<TennojiDecoder> decoder);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiDecoder>, ffi.Int64)>()
external int tennoji_decoder_read_audio(
  ffi.Pointer<TennojiDecoder> decoder,
  int timestamp_us,
);

@ffi.Native<
  ffi.Pointer<TennojiCanvas> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Int32,
    ffi.Int32,
  )
>(isLeaf: true)
external ffi.Pointer<TennojiCanvas> tennoji_canvas_create(
  ffi.Pointer<TennojiEngine> engine,
  int width,
  int height,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void tennoji_canvas_destroy(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Uint32)>(
  isLeaf: true,
)
external void tennoji_canvas_clear(
  ffi.Pointer<TennojiCanvas> canvas,
  int color,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Uint32,
  )
>(isLeaf: true)
external void tennoji_canvas_draw_rect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
  int color,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Pointer<TennojiCanvasImage>,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void tennoji_canvas_draw_image(
  ffi.Pointer<TennojiCanvas> canvas,
  ffi.Pointer<TennojiCanvasImage> image,
  double dx,
  double dy,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void tennoji_canvas_save(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>)>(isLeaf: true)
external void tennoji_canvas_restore(ffi.Pointer<TennojiCanvas> canvas);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void tennoji_canvas_translate(
  ffi.Pointer<TennojiCanvas> canvas,
  double dx,
  double dy,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float, ffi.Float)
>(isLeaf: true)
external void tennoji_canvas_scale(
  ffi.Pointer<TennojiCanvas> canvas,
  double sx,
  double sy,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvas>, ffi.Float)>(
  isLeaf: true,
)
external void tennoji_canvas_rotate(
  ffi.Pointer<TennojiCanvas> canvas,
  double degrees,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TennojiCanvas>,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(isLeaf: true)
external void tennoji_canvas_clip_rect(
  ffi.Pointer<TennojiCanvas> canvas,
  double left,
  double top,
  double width,
  double height,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiCanvas>, ffi.Int)>(isLeaf: true)
external int tennoji_canvas_save_layer(
  ffi.Pointer<TennojiCanvas> canvas,
  int alpha,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiCanvasImage>)>()
external void tennoji_texture_release(ffi.Pointer<TennojiCanvasImage> texture);

@ffi.Native<
  ffi.Pointer<TennojiEncoder> Function(
    ffi.Pointer<TennojiEngine>,
    ffi.Pointer<TennojiEncoderConfig>,
  )
>()
external ffi.Pointer<TennojiEncoder> tennoji_encoder_create(
  ffi.Pointer<TennojiEngine> engine,
  ffi.Pointer<TennojiEncoderConfig> config,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<TennojiEncoder>, ffi.Pointer<TennojiCanvas>)
>()
external int tennoji_encoder_write_frame(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiCanvas> canvas,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TennojiEncoder>,
    ffi.Pointer<TennojiDecoder>,
    ffi.Int64,
  )
>()
external int tennoji_encoder_write_audio(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiDecoder> audio_decoder,
  int duration_us,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<TennojiEncoder>, ffi.Pointer<TennojiDecoder>)
>()
external int tennoji_encoder_drain_audio_queue(
  ffi.Pointer<TennojiEncoder> encoder,
  ffi.Pointer<TennojiDecoder> decoder,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<TennojiEncoder>)>()
external int tennoji_encoder_finalize(ffi.Pointer<TennojiEncoder> encoder);

@ffi.Native<ffi.Void Function(ffi.Pointer<TennojiEncoder>)>()
external void tennoji_encoder_destroy(ffi.Pointer<TennojiEncoder> encoder);

@ffi.Native<
  ffi.Pointer<TennojiParagraphBuilder> Function(
    ffi.Pointer<ffi.Int32>,
    ffi.Uint8,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint8,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Uint8,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Uint16>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<TennojiParagraphBuilder> tennoji_paragraph_builder_create(
  ffi.Pointer<ffi.Int32> encodedStyle,
  int esLength,
  ffi.Pointer<ffi.Uint8> strutData,
  int sdLength,
  ffi.Pointer<ffi.Char> fontFamily,
  ffi.Pointer<ffi.Pointer<ffi.Char>> strutFontFamilies,
  int sffLen,
  double fontSize,
  double height,
  ffi.Pointer<ffi.Uint16> ellipsis,
  ffi.Pointer<ffi.Char> locale,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
  )
>(isLeaf: true)
external bool tennoji_rsuperellipse_contains(
  double px,
  double py,
  double left,
  double top,
  double right,
  double bottom,
  double tlRx,
  double tlRy,
  double trRx,
  double trRy,
  double blRx,
  double blRy,
  double brRx,
  double brRy,
);

final class TennojiEngine extends ffi.Opaque {}

final class TennojiDecoder extends ffi.Opaque {}

final class TennojiEncoder extends ffi.Opaque {}

final class TennojiTexture extends ffi.Opaque {}

final class TennojiCanvas extends ffi.Opaque {}

final class TennojiParagraphBuilder extends ffi.Opaque {}

final class TennojiCanvasImage extends ffi.Opaque {}

enum TennojiHWAccel {
  TENNOJI_HW_ACCEL_AUTO(0),
  TENNOJI_HW_ACCEL_NONE(1);

  final int value;
  const TennojiHWAccel(this.value);

  static TennojiHWAccel fromValue(int value) => switch (value) {
    0 => TENNOJI_HW_ACCEL_AUTO,
    1 => TENNOJI_HW_ACCEL_NONE,
    _ => throw ArgumentError('Unknown value for TennojiHWAccel: $value'),
  };
}

final class TennojiEngineConfig extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int fps;

  external ffi.Pointer<ffi.Char> gpu_backend;
}

final class TennojiEncoderConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> output_path;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int fps;

  external ffi.Pointer<ffi.Char> video_codec;

  external ffi.Pointer<ffi.Char> audio_codec;

  @ffi.Int32()
  external int audio_sample_rate;

  @ffi.Int32()
  external int audio_channels;
}
